services:
  postgres:
    image: postgres:16
    container_name: flask-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flask-app:
    env_file:
      - .env
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flask run

  tests:
    build: .
    container_name: flask-tests
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
    command: pytest tests/ --maxfail=1 --disable-warnings -q

volumes:
  postgres_data:
