services:
  postgres:
    image: postgres:16
    container_name: plan-index-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flask-app:
    env_file:
      - .env
    build: .
    container_name: plan-index-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flask run
    depends_on:
      - postgres

  worker:
    build: .
    container_name: plan-index-worker
    env_file:
      - .env
    volumes:
      - .:/app
    command: python -u src/jobs/runner.py
    depends_on:
      - postgres

  tests:
    build: .
    container_name: plan-index-tests
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
    command: pytest tests/ --maxfail=1 --disable-warnings -q

volumes:
  postgres_data:
